declare class Tools {
    static centerObject(obj: any, centered: any): void;
    add(obj: any, centered?: boolean, loaded?: boolean): any;
    addGroup(obj: any, centered?: boolean, loaded?: boolean): any;
    addImage(obj: any, centered?: boolean, loaded?: boolean): void;
    addElement(obj: any, centered?: boolean, loaded?: boolean): void;
    remove(): false | undefined;
    removeById(id: any): void;
    duplicate(): false | undefined;
    duplicateById(id: any): void;
    copy(): false | undefined;
    paste(): false | undefined;
    set(key: any, value: any): false | undefined;
    setObject(option: any): false | undefined;
    setByObject(obj: any, key: any, value: any): void;
    setById(id: any, key: any, value: any): void;
    setShadow(key: any, value: any): false | undefined;
    loadImage(obj: any, src: any): void;
    setImage(obj: any, src: any): void;
    setImageById(id: any, source: any): void;
    find(obj: any): any;
    findById(id: any): any;
    allSelect(): void;
    select(obj: any): void;
    selectById(id: any): void;
    originScaleToResize(obj: any, width: any, height: any): void;
    scaleToResize(width: any, height: any): void;
    importJSON(json: any, callback: any): void;
    exportJSON(): any;
    getObjects(): any;
    bringForward(): void;
    bringToFront(): void;
    sendBackwards(): void;
    sendToBack(): void;
    clear(workarea?: boolean): void;
    toGroup(): void;
    toActiveSelection(): void;
    static isElementType(type: any): boolean;
    static getOriginObjects(): any;
    static findOriginById(id: any): any;
    static findOriginByIdWithIndex(id: any): any;
    static removeOriginById(id: any): void;
}
export default Tools;
